uvdesk_setup_wizard_routing_resources:
    prefix:   /
    resource: "../../setup/Resources/config/setup.yaml"

uvdesk_setup_wizard_xhr_routing_resources:
    prefix:   /wizard/
    resource: "../../setup/Resources/config/process.yaml"
